---
 - hosts: all
   

   handlers:

   - name: restart iptables
     service: name=iptables state=restarted

   - name: restart httpd
     service: name=httpd state=restarted

   tasks: 

   - name: copy firewall template
     copy: src=templates/etc/sysconfig/iptables dest=/etc/sysconfig/iptables owner=root group=root mode=0600
     notify: restart iptables

   - name: Install http and php etc
     yum: pkg={{ item }} state=installed
     with_items:
        - httpd
        - php
        - php-common
        - php-xml
        - php-mysql
        - php-gd
        - php-tidy
        - php-pear

   - name: Ensure Apache running
     service: name=httpd state=started enabled=yes

   - name: Copy phpinfo for temporary easier development
     copy: src=templates/var/www/html/phpinfo.php dest=/var/www/html/phpinfo.php  mode=0744
     
